<a href="https://colab.research.google.com/github/Achyran/Achyran-TensorFlowNotes/blob/master/00_tenserflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this nootbook, we're going to cover the most fundamentals concepts of tensors using Tensorflow.

More specifically, we're going to cover:
* Introduction to tensors
* Getting Information from Tensors
* Manipulating Tensors
* tensors & NumPy
* using @tf.function
* using GPUs with TensorFlow
* Exerises

#Introduction to Tensors


In [1]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [37]:
# Create Tensors with tf.constant()
scalar = tf.constant(2)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [38]:
# Check of numer of dimensions of a tensor (ndim)
scalar.ndim

0

In [6]:
#Create a vector
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [7]:
# Ceck dimension of a Vector:
vector.ndim

1

In [8]:
# Create a Matrix
matrix = tf.constant([[3,7],
                      [4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 7],
       [4, 5]], dtype=int32)>

In [9]:
# Check dimension of a Matrix
matrix.ndim

2

In [15]:
# Create another Matrix with type
matrixf = tf.constant([[3.,7.],
                      [4.,5.]], dtype=tf.float16) #Specify datetype
matrixf

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3., 7.],
       [4., 5.]], dtype=float16)>

In [25]:
#Creating a Tensor
tensor = tf.constant([[[1,2],[1,2],[1,2]]
                      ,[[1,2],[1,2],[1,2]],
                      [[1,2],[1,2],[1,2]],
                       [[1,2],[1,2],[1,2]]])
tensor


<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]]], dtype=int32)>

In [26]:
#tensor ndim
tensor.ndim

3

In [34]:
#Create a 4D Tensor
tensor4D = tf.constant([
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]])
tensor4D

#The number of shape is the amount of items in the array of the coresponding dimension

<tf.Tensor: shape=(4, 3, 2, 1), dtype=int32, numpy=
array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]], dtype=int32)>

In [40]:
tensor4D.ndim

4

In [43]:
#Create a 5D Tensor
tensor5D = tf.constant([[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ,[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ,[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ,[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ,[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ])
tensor5D

<tf.Tensor: shape=(5, 4, 3, 2, 1), dtype=int32, numpy=
array([[[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]]],



       [[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]]],



       [[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1

In [41]:
tensor5D.ndim

5

What we've created so far:

* Scalar: a single number
* Vecotr: an array of numbers
* Matrix: a 2-dimensional array
* Tensor: a n-dimensional array