<a href="https://colab.research.google.com/github/Achyran/Achyran-TensorFlowNotes/blob/master/Copy_of_00_tenserflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this nootbook, we're going to cover the most fundamentals concepts of tensors using Tensorflow.

More specifically, we're going to cover:
* Introduction to tensors
* Getting Information from Tensors
* Manipulating Tensors
* tensors & NumPy
* using @tf.function
* using GPUs with TensorFlow
* Exerises

#Introduction to Tensors


In [ ]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Create Tensors with tf.constant()
scalar = tf.constant(2)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
# Check of numer of dimensions of a tensor (ndim)
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
# Ceck dimension of a Vector:
vector.ndim

1

In [ ]:
# Create a Matrix
matrix = tf.constant([[3,7],
                      [4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 7],
       [4, 5]], dtype=int32)>

In [ ]:
# Check dimension of a Matrix
matrix.ndim

2

In [ ]:
# Create another Matrix with type
matrixf = tf.constant([[3.,7.],
                      [4.,5.]], dtype=tf.float16) #Specify datetype
matrixf

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3., 7.],
       [4., 5.]], dtype=float16)>

In [ ]:
#Creating a Tensor
tensor = tf.constant([[[1,2],[1,2],[1,2]]
                      ,[[1,2],[1,2],[1,2]],
                      [[1,2],[1,2],[1,2]],
                       [[1,2],[1,2],[1,2]]])
tensor


<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]]], dtype=int32)>

In [ ]:
#tensor ndim
tensor.ndim

3

In [ ]:
#Create a 4D Tensor
tensor4D = tf.constant([
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]])
tensor4D

#The number of shape is the amount of items in the array of the coresponding dimension

<tf.Tensor: shape=(4, 3, 2, 1), dtype=int32, numpy=
array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]], dtype=int32)>

In [ ]:
tensor4D.ndim

4

In [ ]:
#Create a 5D Tensor
tensor5D = tf.constant([[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ,[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ,[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ,[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ,[
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]],
                       [[[1],[1]],
                        [[1],[1]],
                        [[1],[1]]]]
                        ])
tensor5D

<tf.Tensor: shape=(5, 4, 3, 2, 1), dtype=int32, numpy=
array([[[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]]],



       [[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]]],



       [[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1

In [ ]:
tensor5D.ndim

5

What we've created so far:

* Scalar: a single number
* Vecotr: an array of numbers
* Matrix: a 2-dimensional array
* Tensor: a n-dimensional array

### Creating Veriable Tensors


In [ ]:
variable_tensor = tf.Variable([1,2])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
#Assing
variable_tensor.assign([2,3])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [ ]:
#Assing on a deeper dimmension
variable_tensor[0].assign([6])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 3], dtype=int32)>

In [ ]:
#Playing variable Matrix
variable_Matrix = tf.Variable([[[1,2],[3,4]],[[5,6],[7,8]]])
variable_Matrix

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [ ]:
#Assingin in the first dimension
variable_Matrix.assign([[[1,2],[3,4]],[[5,6],[7,8]]])  #Assingin on the first dimension takes a tensor with the same Shape
variable_Matrix

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [ ]:
#Assingin in the second dimension
variable_Matrix[1].assign([[5,6],[7,8]])  #Assingin on the lower dimension takes a shape wit the shape of the lower dimenions (in this case (2,2))
variable_Matrix                           #at the specified index (in this case in the las row of the matrix)

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [ ]:
#To be Fixed

#Assingin in the third  dimension
#variable_Matrix[1][0].assign([7,8])  #Assingin on the lower dimension takes a shape wit the shape of the lower dimenions (in this case (2,2))
variable_Matrix[1][0]                   #at the specified index (in this case in the las row of the matrix)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>

### Creating Random Tensors

Random transors are thensors of abitrary size whitch contain random Numbers

In [ ]:
tensor_factory = tf.random.Generator.from_seed(42) #Generates a Tensor facotry Comparable the the Random rand = new Random(42) in C#
random_1 = tensor_factory.normal(shape= (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42).normal(shape=(3,2)) #Create the same tensor again
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

###Shuffle Tensors


In [ ]:
#Shuffle a Tensor (valuable when you shuffle yout data so the inherret order does not interfere with learning)

not_shuffled = tf.constant([[2,3],[3,4],[4,5]])

#Shuffle our tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
#Shuffle the same every time
tf.random.set_seed(42)                           #sets the the global seed
tf.random.shuffle(not_shuffled, seed = 5)        #uses the global seed in combination with the operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4],
       [4, 5]], dtype=int32)>